# -*- coding: utf-8 -*-
"""House-Recognition-v1(0.98)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15OgwRNhAI33pUWSlQSenNpOQkUET2kw3
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

super_ai_engineer_season_6_individual_hackathon_house_recognition_path = kagglehub.competition_download('super-ai-engineer-season-6-individual-hackathon-house-recognition')

print('Data source import complete.')

!pip -q install timm

import os
import gc
import math
import random
import warnings
from copy import deepcopy
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

import timm
from timm.data import resolve_data_config
from timm.data.transforms_factory import create_transform

from torchvision import transforms as T
from torchvision.transforms import InterpolationMode

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
from sklearn.utils.class_weight import compute_class_weight

warnings.filterwarnings("ignore")

CFG = {
    "seed": 42,
    "model_name": "mobilenetv3_large_100",
    "num_folds": 5,
    "epochs": 15,
    "batch_size": 32,
    "lr": 2e-4,
    "weight_decay": 1e-4,
    "label_smoothing": 0.05,
    "num_workers": 2,
    "tta": True,
    "max_grad_norm": 5.0,
    "drop_rate": 0.2,
}

INPUT_ROOT = Path("/kaggle/input")
WORK_DIR = Path("/kaggle/working")
COMP_NAME = "super-ai-engineer-season-6-individual-hackathon-house-recognition"
IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Torch:", torch.__version__)
print("Device:", device)
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

def seed_everything(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = False
    torch.backends.cudnn.benchmark = True

seed_everything(CFG["seed"])

def find_dataset_root(input_root: Path, comp_name: str):
    exact_dir = input_root / comp_name
    if exact_dir.exists():
        return exact_dir
    candidates = [p for p in input_root.iterdir() if p.is_dir() and comp_name in p.name]
    if candidates:
        return candidates[0]
    return input_root

def find_file_by_name(root: Path, filename: str):
    matches = [p for p in root.rglob(filename) if p.is_file()]
    return matches[0] if matches else None

def find_dir_by_name(root: Path, dirname: str):
    matches = [p for p in root.rglob(dirname) if p.is_dir()]
    return matches[0] if matches else None

def is_image_file(path: Path):
    return path.suffix.lower() in IMAGE_EXTS

def build_image_map(image_dir: Path):
    image_files = [p for p in image_dir.rglob("*") if p.is_file() and is_image_file(p)]
    mapping = {}
    for p in image_files:
        name = p.name.strip()   # abc.jpg
        stem = p.stem.strip()   # abc
        pstr = str(p)
        if name not in mapping:
            mapping[name] = pstr
        if stem not in mapping:
            mapping[stem] = pstr
    return mapping, image_files

DATA_ROOT = find_dataset_root(INPUT_ROOT, COMP_NAME)
TRAIN_DIR = find_dir_by_name(DATA_ROOT, "train")
TEST_DIR = find_dir_by_name(DATA_ROOT, "test")
TRAIN_CSV = find_file_by_name(DATA_ROOT, "train.csv")
SUBMIT_CSV = find_file_by_name(DATA_ROOT, "submit.csv") or find_file_by_name(DATA_ROOT, "sample_submission.csv")

print("DATA_ROOT :", DATA_ROOT)
print("TRAIN_DIR :", TRAIN_DIR)
print("TEST_DIR  :", TEST_DIR)
print("TRAIN_CSV :", TRAIN_CSV)
print("SUBMIT_CSV:", SUBMIT_CSV)

if TRAIN_DIR is None or TEST_DIR is None or TRAIN_CSV is None or SUBMIT_CSV is None:
    raise FileNotFoundError("หา train/test/train.csv/submit.csv ไม่ครบ")

train_meta = pd.read_csv(TRAIN_CSV)
submit_meta = pd.read_csv(SUBMIT_CSV)

train_meta.columns = [c.strip().lower() for c in train_meta.columns]
submit_meta.columns = [c.strip().lower() for c in submit_meta.columns]

print("train.csv columns :", list(train_meta.columns))
print("submit.csv columns:", list(submit_meta.columns))

possible_id_cols = ["id", "image_id", "image_name", "filename", "file", "image", "img", "name"]
possible_label_cols = ["answer", "label", "class", "target", "category"]

ID_COL = next((c for c in possible_id_cols if c in train_meta.columns), None)
LABEL_COL = next((c for c in possible_label_cols if c in train_meta.columns), None)
SUBMIT_ID_COL = next((c for c in possible_id_cols if c in submit_meta.columns), None)

if ID_COL is None:
    raise ValueError(f"หา id column ไม่เจอใน train.csv: {list(train_meta.columns)}")
if LABEL_COL is None:
    raise ValueError(f"หา label column ไม่เจอใน train.csv: {list(train_meta.columns)}")
if SUBMIT_ID_COL is None:
    raise ValueError(f"หา id column ไม่เจอใน submit.csv: {list(submit_meta.columns)}")

train_image_map, train_image_files = build_image_map(TRAIN_DIR)
test_image_map, test_image_files = build_image_map(TEST_DIR)

print("Train images:", len(train_image_files))
print("Test images :", len(test_image_files))

train_df = train_meta[[ID_COL, LABEL_COL]].copy()
train_df.columns = ["id", "label_raw"]
train_df["id"] = train_df["id"].astype(str).str.strip()
train_df["filepath"] = train_df["id"].map(train_image_map)

test_df = submit_meta.copy()
test_df["id"] = test_df[SUBMIT_ID_COL].astype(str).str.strip()
test_df["filepath"] = test_df["id"].map(test_image_map)

missing_train = train_df["filepath"].isna().sum()
missing_test = test_df["filepath"].isna().sum()

print("Missing train paths:", missing_train)
print("Missing test paths :", missing_test)

if missing_train > 0:
    print(train_df.loc[train_df["filepath"].isna(), ["id"]].head(20))
    raise ValueError("มี train image บางส่วนจับคู่กับ train.csv ไม่ได้")
if missing_test > 0:
    print(test_df.loc[test_df["filepath"].isna(), ["id"]].head(20))
    raise ValueError("มี test image บางส่วนจับคู่กับ submit.csv ไม่ได้")

label_values = sorted(train_df["label_raw"].unique().tolist())
label2idx = {label: idx for idx, label in enumerate(label_values)}
idx2label = {idx: label for label, idx in label2idx.items()}
train_df["label"] = train_df["label_raw"].map(label2idx).astype(int)
NUM_CLASSES = len(label_values)

print("NUM_CLASSES:", NUM_CLASSES)
print(train_df["label_raw"].value_counts())
train_df.head()

tmp_model = timm.create_model(CFG["model_name"], pretrained=True, num_classes=NUM_CLASSES)
data_cfg = resolve_data_config({}, model=tmp_model)
print("data_cfg:", data_cfg)

img_size = data_cfg["input_size"][-1]
mean = data_cfg["mean"]
std = data_cfg["std"]
interpolation = InterpolationMode.BICUBIC

train_transform = T.Compose([
    T.RandomResizedCrop(img_size, scale=(0.75, 1.0), interpolation=interpolation),
    T.RandomHorizontalFlip(p=0.5),
    T.RandomVerticalFlip(p=0.1),
    T.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.05),
    T.RandomRotation(degrees=10),
    T.ToTensor(),
    T.Normalize(mean=mean, std=std),
    T.RandomErasing(p=0.25, scale=(0.02, 0.12), ratio=(0.3, 3.3), value="random"),
])

valid_transform = create_transform(**data_cfg)

class HouseDataset(Dataset):
    def __init__(self, df, transform, train=True):
        self.df = df.reset_index(drop=True)
        self.transform = transform
        self.train = train

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img = Image.open(row["filepath"]).convert("RGB")
        img = self.transform(img)
        if self.train:
            return img, int(row["label"])
        return img

print("Train samples:", len(train_df))
print("Test samples :", len(test_df))

def build_model():
    model = timm.create_model(
        CFG["model_name"],
        pretrained=True,
        num_classes=NUM_CLASSES,
        drop_rate=CFG["drop_rate"],
    )
    return model.to(device)

def get_loaders(train_fold_df, valid_fold_df):
    train_ds = HouseDataset(train_fold_df, train_transform, train=True)
    valid_ds = HouseDataset(valid_fold_df, valid_transform, train=True)
    test_ds = HouseDataset(test_df, valid_transform, train=False)

    train_loader = DataLoader(
        train_ds,
        batch_size=CFG["batch_size"],
        shuffle=True,
        num_workers=CFG["num_workers"],
        pin_memory=True,
        drop_last=False,
    )
    valid_loader = DataLoader(
        valid_ds,
        batch_size=CFG["batch_size"] * 2,
        shuffle=False,
        num_workers=CFG["num_workers"],
        pin_memory=True,
        drop_last=False,
    )
    test_loader = DataLoader(
        test_ds,
        batch_size=CFG["batch_size"] * 2,
        shuffle=False,
        num_workers=CFG["num_workers"],
        pin_memory=True,
        drop_last=False,
    )
    return train_loader, valid_loader, test_loader

def train_one_epoch(model, loader, criterion, optimizer, scaler):
    model.train()
    running_loss = 0.0
    all_preds, all_targets = [], []

    for images, targets in loader:
        images = images.to(device, non_blocking=True)
        targets = targets.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)

        with torch.cuda.amp.autocast(enabled=torch.cuda.is_available()):
            logits = model(images)
            loss = criterion(logits, targets)

        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(model.parameters(), CFG["max_grad_norm"])
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item() * images.size(0)
        preds = logits.argmax(dim=1)

        all_preds.append(preds.detach().cpu().numpy())
        all_targets.append(targets.detach().cpu().numpy())

    all_preds = np.concatenate(all_preds)
    all_targets = np.concatenate(all_targets)
    loss = running_loss / len(loader.dataset)
    acc = accuracy_score(all_targets, all_preds)
    return loss, acc

@torch.no_grad()
def predict_probs(model, loader, tta=False):
    model.eval()
    probs_all = []

    for batch in loader:
        if isinstance(batch, (list, tuple)):
            images = batch[0]
        else:
            images = batch

        images = images.to(device, non_blocking=True)

        with torch.cuda.amp.autocast(enabled=torch.cuda.is_available()):
            logits = model(images)
            probs = torch.softmax(logits, dim=1)

            if tta:
                logits_flip = model(torch.flip(images, dims=[3]))
                probs_flip = torch.softmax(logits_flip, dim=1)
                probs = (probs + probs_flip) / 2.0

        probs_all.append(probs.detach().cpu().numpy())

    return np.concatenate(probs_all, axis=0)

@torch.no_grad()
def evaluate(model, loader, criterion, tta=False):
    model.eval()
    running_loss = 0.0
    all_probs, all_targets = [], []

    for images, targets in loader:
        images = images.to(device, non_blocking=True)
        targets = targets.to(device, non_blocking=True)

        with torch.cuda.amp.autocast(enabled=torch.cuda.is_available()):
            logits = model(images)
            loss = criterion(logits, targets)
            probs = torch.softmax(logits, dim=1)

            if tta:
                logits_flip = model(torch.flip(images, dims=[3]))
                probs_flip = torch.softmax(logits_flip, dim=1)
                probs = (probs + probs_flip) / 2.0

        running_loss += loss.item() * images.size(0)
        all_probs.append(probs.detach().cpu().numpy())
        all_targets.append(targets.detach().cpu().numpy())

    all_probs = np.concatenate(all_probs)
    all_targets = np.concatenate(all_targets)
    preds = all_probs.argmax(axis=1)
    loss = running_loss / len(loader.dataset)
    acc = accuracy_score(all_targets, preds)
    return loss, acc, all_probs

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.arange(NUM_CLASSES),
    y=train_df["label"].values
)
class_weights = torch.tensor(class_weights, dtype=torch.float32, device=device)
print("class_weights:", class_weights)

skf = StratifiedKFold(n_splits=CFG["num_folds"], shuffle=True, random_state=CFG["seed"])

oof_probs = np.zeros((len(train_df), NUM_CLASSES), dtype=np.float32)
test_probs = np.zeros((len(test_df), NUM_CLASSES), dtype=np.float32)
fold_scores = []

for fold, (tr_idx, va_idx) in enumerate(skf.split(train_df, train_df["label"]), 1):
    print(f"\n========== Fold {fold}/{CFG['num_folds']} ==========")

    train_fold_df = train_df.iloc[tr_idx].reset_index(drop=True)
    valid_fold_df = train_df.iloc[va_idx].reset_index(drop=True)

    train_loader, valid_loader, test_loader = get_loaders(train_fold_df, valid_fold_df)

    model = build_model()
    criterion = nn.CrossEntropyLoss(
        weight=class_weights,
        label_smoothing=CFG["label_smoothing"]
    )
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=CFG["lr"],
        weight_decay=CFG["weight_decay"]
    )
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer,
        T_max=CFG["epochs"]
    )
    scaler = torch.cuda.amp.GradScaler(enabled=torch.cuda.is_available())

    best_acc = -1
    best_path = WORK_DIR / f"best_fold_{fold}.pth"

    for epoch in range(1, CFG["epochs"] + 1):
        train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, scaler)
        val_loss, val_acc, _ = evaluate(model, valid_loader, criterion, tta=CFG["tta"])
        scheduler.step()

        print(
            f"Fold {fold} | Epoch {epoch:02d}/{CFG['epochs']} | "
            f"train_loss={train_loss:.4f} train_acc={train_acc:.4f} | "
            f"val_loss={val_loss:.4f} val_acc={val_acc:.4f}"
        )

        if val_acc > best_acc:
            best_acc = val_acc
            torch.save(model.state_dict(), best_path)

    print(f"Best val_acc for fold {fold}: {best_acc:.5f}")
    fold_scores.append(best_acc)

    model.load_state_dict(torch.load(best_path, map_location=device))

    _, _, fold_valid_probs = evaluate(model, valid_loader, criterion, tta=CFG["tta"])
    fold_test_probs = predict_probs(model, test_loader, tta=CFG["tta"])

    oof_probs[va_idx] = fold_valid_probs
    test_probs += fold_test_probs / CFG["num_folds"]

    del model, train_loader, valid_loader, test_loader
    torch.cuda.empty_cache()
    gc.collect()

oof_pred = oof_probs.argmax(axis=1)
cv_acc = accuracy_score(train_df["label"].values, oof_pred)

print("\nFold scores:", [round(s, 5) for s in fold_scores])
print("CV Accuracy:", round(cv_acc, 6))

test_pred_idx = test_probs.argmax(axis=1)
test_pred_label = [idx2label[int(i)] for i in test_pred_idx]

submission = submit_meta.copy()

possible_submit_label_cols = ["answer", "label", "class", "target", "category"]
submit_label_col = next((c for c in possible_submit_label_cols if c in submission.columns), None)
if submit_label_col is None:
    submit_label_col = "class"

submission[submit_label_col] = test_pred_label

submission_path = WORK_DIR / "submission_timm_mobilenetv3_5fold_tta.csv"
submission.to_csv(submission_path, index=False)

oof_df = train_df[["id", "label_raw", "label"]].copy()
oof_df["pred_idx"] = oof_pred
oof_df["pred_label"] = [idx2label[int(i)] for i in oof_pred]
oof_df["correct"] = (oof_df["label"].values == oof_pred).astype(int)
oof_path = WORK_DIR / "oof_predictions.csv"
oof_df.to_csv(oof_path, index=False)

print("Saved submission:", submission_path)
print("Saved oof       :", oof_path)
print(submission.head())



